### ISSUE TITLE
glyphicons missing in the footer

### ISSUE THREAD

**Issue by staticnull** [GR8conf/website#40]
![gr8conf_us](https://user-images.githubusercontent.com/225701/42735153-d88237fa-8814-11e8-882e-27e14391957b.jpg)

The left/right chevons in the carrosel are missing. Along with the twitter/youtube/mail FA icons in the bottom footer. 

js erros in the console 

glyphicons-halflings-regular.woff2:1 Failed to load resource: the server responded with a status of 404 ()
glyphicons-halflings-regular.woff:1 Failed to load resource: the server responded with a status of 404 ()
glyphicons-halflings-regular.ttf:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by staticnull** [comment]
I think the three files mentioned are missing from the project and come from Bootstrap itself. I will try and take a look this afternoon if I get some time to fix this.

**Comment by staticnull** [comment]
Dang, I'm getting the following plugin error when I try to start up the project.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Bad <init> method call from inside of a branch
  Exception Details:
    Location:
      grails/plugins/rest/client/RestBuilder.<init>()V @83: invokespecial
    Reason:
      Error exists in the bytecode

**Comment by staticnull** [comment]
Getting the following with a longer stack trace when trying to run the project. 

> ./gradlew bootRun

> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.grails:grails-gradle-plugin:3.3.6.
....

Looks like it may be related to this known issue but the workaround didn't fix my issue. 
https://github.com/grails/grails-core/issues/11045

**Comment by erichelgeson** [comment]
I cant reproduce these issues - `./gradlew bootRun` works, using java 8u172 - the `grails-gradle-plugin` issue is only for multibuild projects.

Maybe blow away your gradle/m2 cache?

**Comment by staticnull** [comment]
figured out my problem - builds fine now
